### ISSUE TITLE
添加指纹-[全英文组件名称]: 

### ISSUE THREAD

**Issue by cn-kali-team** [cn-kali-team/fingerprint-hub-actions#2]
### 测试目标

https://www.example.com/

### 指纹的Yaml

```yaml
name: 0example
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - <title>Example Domain</title>
    favicon_hash: []
```
